- .babelrc
- package-lock.json
- package.json
- server/server.js
- webpack.config.js
@shabbyblue16 , @tm2838 please review. thanks!
> initialize repo; set up directory structure

- README.md
@tm2838 @shabbyblue16 I noticed this was in gLearn as a deliverable, so I updated the readme with instructions on how to start the app.
> update README with app setup instructions

- package-lock.json
- package.json
- webpack.config.js
installed jest as dev dependency per https://jestjs.io/docs/getting-started
modified package.json and webpack.config.js per https://jestjs.io/docs/webpack
note: I did not include configurations for CSS or image files as that seems premature at this time. Also, the file paths may need to be modified to suit our directory structure.
> install jest; modify webpack config file accordingly

- .gitignore
- client/dist/index.html
- client/src/components/app.jsx
- client/src/index.jsx
- package.json
- server/server.js
- webpack.config.js
Tested our set up and server side rendering. Seems to be working!
> server side rendering

- client/src/components/app.test.js
- package-lock.json
- package.json
- webpack.config.js
As developers, we need testing frameworks to be set up so that we can write unit tests efficiently during app development. `React Testing Library` is used for DOM testing, which would be useful to test components rendering and user interactions.
run `npm test`, and it should look like this in terminal:
https://trello.com/c/D4iF66FG
> Add React Testing Library

- package-lock.json
- package.json
- server/server.js
Please save your api keys in the .env file as API_KEY so we all have the same config.
> install dotenv, create .env file, configure server.js

- client/src/components/relatedProducts/Button.jsx
- client/src/components/relatedProducts/ProductCard.jsx
- client/src/components/relatedProducts/styles.css
This is a button that will appear on each related product card or outfit card and will render as a star or as a circle with an X inside it respectively. I also added the individual product card in which the button will display, as well as the stylesheet to display the card component as a card.
No test yet as it will not render until the Product Card, is imported into a Related Products component and / or Outfit component. 
Note that test to render <App /> is failing because of not being configured for CSS files loaded. It was original just one pull request for one issue, but I committed the product card component too because they go together and it seemed more efficient this way.
https://trello.com/c/MmsS4wKj/86-s-create-product-card-button …
> build Button conditionally star or X

- client/src/components/common/fontAwesomeIcons.js
- client/src/components/common/starRating.jsx
- client/src/components/relatedProducts/Button.jsx
- client/src/components/relatedProducts/Modal.jsx
- client/src/components/relatedProducts/ProductCard.jsx
- client/src/components/relatedProducts/RelatedProducts.jsx
- server/products.js
- server/server.js
This is a skeleton of the comparison modal that pops up when a user clicks on the star button of product card in the related products carousel.
Manual testing still - click on star icon of one of the product cards in the related products carousel, and the modal should pop up beneath the carousel.
I modified some of the routes to accept an option product id parameter because I have to do an api call to get product and style information for each related product. I also fixed some linting errors that came up as I imported commony used files (e.g. starRating).
https://trello.com/c/mvj1Kal1/84-s-create-comparison-modal
> implement modal skeleton

- README.md
- client/src/components/app.jsx
- client/src/components/common/banner.jsx
- client/src/components/common/commonUI.module.css
- client/src/components/common/fontAwesomeIcons.js
- client/src/components/common/starRating.jsx
- client/src/components/common/starRating.module.css
- client/src/components/productReviews/productReviews.jsx
- client/src/components/productReviews/productReviews.module.css
- client/src/components/productReviews/sortingDropdown.jsx
Added a dropdown for sorting reviews based on the selected criterion.
Added a banner on top of the page.
Manual test:
verify that there is no regression
verify that the dropdown by default shows 'relevant'
verify that the dropdown is clickable
verify that  the dropdown shows the newly selected value on select
https://trello.com/c/jMUbbzFV
> Sort review skeleton

- client/src/components/app.jsx
- client/src/components/common/fontAwesomeIcons.js
- client/src/components/relatedProducts/Button.jsx
- client/src/components/relatedProducts/Outfit.jsx
- client/src/components/relatedProducts/ProductCard.jsx
- server/server.js
skeleton for outfit carousel
manually. Add card will render upon page loading. Click plus sign to add product card for current product to outfit.
fixed bug in removal from carousel function
https://trello.com/c/bIXYE5wT/23-create-outfit-list-component
> implement outfit carousel skeleton

- client/src/components/productOverview/OverviewContainer.jsx
- client/src/components/productOverview/ProductSummary.jsx
- client/src/components/productOverview/StyleList.jsx
- client/src/components/productOverview/testingLibrary/ImageGallery.test.js
- client/src/components/productOverview/testingLibrary/ImageNavButton.test.js
- client/src/components/productOverview/testingLibrary/ImageThumbnail.test.js
- client/src/components/productOverview/testingLibrary/ProductInfo.test.js
- client/src/components/productOverview/testingLibrary/ProductName.test.js
- client/src/components/productOverview/testingLibrary/ProductRating.test.js
- client/src/components/productOverview/testingLibrary/ProductSummary.test.js
- client/src/components/productOverview/testingLibrary/SelectQty.test.js
- client/src/components/productOverview/testingLibrary/SelectSize.test.js
- client/src/components/productOverview/testingLibrary/Style.test.js
- client/src/components/productOverview/testingLibrary/StyleList.test.js
- package.json
Added test suites for these two components. Also added a test coverage script in package.json
Run npm test; or npm run test:coverage to get coverage numbers.
Plan on writing more tests by the end of the day
https://trello.com/c/mLJU7R1E/100-write-unit-tests-for-components-rendering
> ProductSummary and StyleList render tests

- client/src/components/relatedProducts/test/outfit.test.js
- client/src/components/relatedProducts/test/productCard.test.js
- client/src/components/relatedProducts/test/relatedProducts.test.js
- package-lock.json
refactor related products widget component tests into separate units
run npm test
to conform with best practices
https://trello.com/c/QB4OcVyk/121-refactor-relatedproducts-widget-tests-into-separate-test-suites-for-each-component
> refactor relatedProducts widget component tests into separate units

- client/src/components/productReviews/sortingDropdown.jsx
- client/src/components/productReviews/test/review.test.jsx
- client/src/components/productReviews/test/sortingDropdown.test.jsx
Just added two more test suites before the release.
`npm test`
https://trello.com/c/w2IjVzuh
> more unit tests

- client/src/components/productOverview/ImageGallery.jsx
- client/src/components/productOverview/ImageNavButton.jsx
- client/src/components/productOverview/ProductRating.jsx
- client/src/components/productOverview/testingLibrary/ImageGallery.test.js
- client/src/components/productOverview/testingLibrary/ProductRating.test.js
- client/src/components/productOverview/testingLibrary/StyleList.test.js
- client/src/fixtures/testProduct.json
Added a couple tests in ImageGallery checking for component rendering and clicking on thumbnail images
`npm test`
https://trello.com/c/mLJU7R1E/100-write-unit-tests-for-components-rendering
> Unit tests for ImageGallery

- client/src/components/relatedProducts/Modal.jsx
- client/src/components/relatedProducts/test/modal.test.js
tests for modal rendering - render value for current product, for related product, for when features are unique and in common, as well as rendering check marks for when value is boolean true.
run npm test
starting to appreciate the concept of testing for more than just passing assignments. Writing these tests actually helped me find a couple of bugs, which are now fixed.
https://trello.com/c/OVHhJzcv/127-m-write-tests-for-modal-rendering
> implement tests for modal rendering

- client/src/actions/productReviews/changeFilters.js
- client/src/components/productReviews/productReviews.jsx
- client/src/components/productReviews/productReviews.module.css
- client/src/components/productReviews/ratings.jsx
- client/src/components/productReviews/sortingDropdown.jsx
- client/src/components/productReviews/starBreakdown.jsx
- client/src/components/productReviews/starBreakdownBar.jsx
- client/src/components/productReviews/test/starBreakdown.test.jsx
- client/src/reducers/productReviews/filtersReducer.js
- client/src/reducers/rootReducer.js
- server/reviews.js
- server/server.js
Replace the placeholder with functional star rating breakdowns.
Manual test:
1. background color for each bar should change on hover
2. click on each bar would add that rating as a filter, and the review list would display filtered reviews
3. filters are additive
4. click on the same bar for a second time would remove that filter
5. click on 'remove filters' would remove all filters
It's weird that the number of reviews doesn't match the sum of each star rating from reviewMeta. I used the latter to calculate percentage.
https://trello.com/c/5U4CMe25
https://trello.com/c/I7stBDPB
> Star breakdown bar

- client/src/actions/fetchProduct.js
- client/src/components/app.jsx
- client/src/components/productOverview/OverviewContainer.jsx
- client/src/components/productOverview/StyleList.jsx
- package-lock.json
- package.json
- server/server.js
Installed react-router. Wrapped components with Router. Refactored `OverviewContainer` component and `fetchProduct` action to accept productId argument. Changed route of `app.use()` in server
In browser navigate to localhost:3000/product/:productId where productId is any valid id number (starting at 47421)
- Using localhost:3000 without the /product route plus productId parameter won't work anymore
- I got stuck trying to make this work using a Class component. Refactored `OverviewContainer` into a functional component and used `useEffect()` instead of `componentDidMount()` to make the api call
- No error handling yet so using an invalid productId number may break the app
https://trello.com/c/1RbInPS8/120-install-and-implement-react-router
> Added product navigation by url with react-router

- client/dist/index.html
- client/src/actions/postInteractions.js
- client/src/components/Wrapper.jsx
- client/src/components/productOverview/OverviewContainer.jsx
- client/src/components/relatedProducts/RelatedProducts.jsx
- client/src/components/withClickTracker.jsx
- package-lock.json
- server/interactions.js
- server/server.js
Created a HOC with an event listener that we can wrap around our highest level components (e.g. `OverviewContainer`). Added a `postInteractions` action that makes the post request to the server, and then a post handler in our server that makes the call to the api. Clicking on any element in a widget (as long as the main component is wrapped) should get a 201 back from the api that's logged in the server and client.
Click on any element in the product overview widget, open up the console and make sure that a 201 is logged.
- Make sure that the highest level element in your widget has an id equal to the name of the widget. So in `OverviewContainer` the top `<div>` has an id of 'product-overview'.
- Pass in a string equal to that id as the second argument when wrapping your widget component …
> Interactions wrapper

- client/src/components/ratingsAndReviews/reviewModal/reviewModal.jsx
Users should be able to submit 5 photos along with a review.
Click on the `add a review` button, when the modal pops up, scroll down to the bottom and click `upload file`, the photo uploaded should show up immediately
After five photos are uploaded, the `upload` button is disabled.
Click on an uploaded photo would delete that photo.
https://trello.com/c/UkFXW4EA
> ability to upload photos

- client/src/components/ratingsAndReviews/ratingsAndReviews.module.css
- client/src/components/ratingsAndReviews/reviewModal/reviewModal.jsx
- client/src/components/ratingsAndReviews/reviewModal/reviewModalCharRating.jsx
- client/src/components/withClickTracker.jsx
Added the review body input which requires a min character of 50 and max character of 1000, also provided visual aid for how many characters are left to reach minimum.
Fixed console error related to the radio buttons.
Wrapping the widget with click tracker prevents the default behavior for uploading photos and select radio buttons, so fixed that as well.
Open up the write new review modal, type sth in the `review body` field, and verify that the counter text below updates as you type. It also change to 'Minimum reached' after 50 characters are typed.
https://trello.com/c/86VHqceY
> add review body input

- client/src/components/Wrapper.jsx
- client/src/components/app.jsx
- client/src/components/relatedProducts/Button.jsx
- client/src/components/relatedProducts/Modal.jsx
- client/src/components/relatedProducts/ProductCard.jsx
- client/src/components/relatedProducts/RelatedProducts.jsx
- client/src/components/relatedProducts/RelatedProductsContainer.jsx
- client/src/components/relatedProducts/test/productCard.test.js
- client/src/components/relatedProducts/test/relatedProducts.test.js
- client/src/components/withClickTracker.jsx
fix broken related products tests 
also found that modal is now broken. got error when clicking star to trigger modal pop up that postInteractions failed to fetch. Changing classname to tagname seems to have resolved error (line 14). Please double check how this affects other click events.
run npm test
https://trello.com/c/zzbZfyaU/148-s-fix-broken-related-products-tests
https://trello.com/c/mhXF6RZf/149-s-fix-related-products-interactions-error-when-clicking-on-star-to-trigger-modal
> Error handling

- client/src/components/common/fontAwesomeIcons.js
- client/src/components/ratingsAndReviews/ratings/productBreakdown.jsx
- client/src/components/ratingsAndReviews/ratings/productBreakdownBar.jsx
- client/src/components/ratingsAndReviews/ratings/starBreakdown.jsx
- client/src/components/ratingsAndReviews/ratingsAndReviews.module.css
- client/src/components/ratingsAndReviews/reviews/reviewButtons.jsx
Kicked out the product breakdown placeholder and added the real component.
Switch url to different products and verify that the little carets change position.
https://trello.com/c/F4B3KxRn
> Product breakdown

- README.md
- client/src/actions/postInteractions.js
- client/src/components/ratingsAndReviews/ratings/productBreakdownBar.jsx
- client/src/components/relatedProducts/Button.jsx
- client/src/components/relatedProducts/Outfit.jsx
- client/src/components/relatedProducts/ProductCard.jsx
- client/src/components/relatedProducts/RelatedProducts.jsx
- client/src/components/withClickTracker.jsx
- client/src/index.jsx
- client/src/reducers/rootReducer.js
- server/interactions.js
- server/server.js
Want to do some clean up before we release to main. There is no function change, just deleted some unused comments, and commented out a few console logs.
Also updated the url in README.
> clean up dev

- client/src/components/relatedProducts/test/modal.test.js
- client/src/components/relatedProducts/test/productCard.test.js
- client/src/components/relatedProducts/test/relatedProducts.test.js
- client/src/components/relatedProducts/test/relatedProductsContainer.test.js
add more tests
run npm test
should finally have relatedproducts at 60%
note I added a lot of npm packages trying to get things to work, but I don't think you actually need any of them right now (and actually I don't think I pushed changes to the package.json anyway, just the test files).
https://trello.com/c/iJ4Yu4zk/155-add-related-products-tests
> add more tests

- .gitignore
- client/src/components/common/starRating.jsx
- client/src/components/ratingsAndReviews/ratings/ratings.jsx
- client/src/components/ratingsAndReviews/ratings/starBreakdown.jsx
- client/src/components/ratingsAndReviews/ratingsAndReviews.module.css
- client/src/components/ratingsAndReviews/reviewModal/reviewModal.jsx
- client/src/components/ratingsAndReviews/reviews/review.jsx
- client/src/components/ratingsAndReviews/reviews/reviewsList.jsx
Added functionality to `StarRating` component, so that it can dynamically render ratings by passing in the rating score.
It also accepts a `onClick` function (by default does nothing, but allows for function defined outside the component), which allows user to click and fill in starts when writing a new review.
Switch to different products and verify that next to the overall rating score, the star rating changes and can display up to 1/4 star.
Open up the write new review modal and verify that the overall star rating is clickable, and displays the meaning of the selection.
https://trello.com/c/6XwkPLUT
https://trello.com/c/9RQU66IQ
> complete star rating functionality

- client/src/components/ratingsAndReviews/ratings/starBreakdown.jsx
- client/src/components/ratingsAndReviews/reviewModal/reviewModal.jsx
- client/src/components/ratingsAndReviews/reviewModal/reviewModalCharRating.jsx
- client/src/components/ratingsAndReviews/test/productBreakdown.test.jsx
- client/src/components/ratingsAndReviews/test/reviewModal.test.jsx
- client/src/components/ratingsAndReviews/test/reviewModalCharRating.test.jsx
- client/src/components/ratingsAndReviews/test/starBreakdown.test.jsx
- client/src/components/relatedProducts/test/relatedProductsContainer.test.js
- client/src/fixtures/testStore.js
Just some tests.
npm test
https://trello.com/c/N1PI7REj
> Test ratings and reviews

- client/src/components/relatedProducts/Button.jsx
- client/src/components/relatedProducts/ProductCard.jsx
- client/src/components/relatedProducts/RelatedProducts.jsx
- server/server.js
api call for star ratings for related products. pass data into StarRatings component rendered on each Product Card in Related Products carousel to render star rating for each related product.
manually. when related products carousel renders, each card should have its own respective star rating.
also added key for Modal. Bad practice, but it was so small, it seemed more efficient just to throw it in here too.
https://trello.com/c/VlsYcMLL/167-m-api-call-for-star-rating
https://trello.com/c/qabtNDGR/132-s-provide-modal-with-key-attribute
> Related ratings

- client/src/components/ratingsAndReviews/ratings/productBreakdownBar.jsx
- client/src/components/ratingsAndReviews/ratings/ratings.jsx
- client/src/components/ratingsAndReviews/ratings/starBreakdown.jsx
- client/src/components/ratingsAndReviews/ratings/starBreakdownBar.jsx
- client/src/components/ratingsAndReviews/ratingsAndReviews.module.css
- client/src/components/ratingsAndReviews/reviewModal/reviewModal.jsx
- client/src/components/ratingsAndReviews/reviewModal/reviewModalContent.jsx
- client/src/components/ratingsAndReviews/reviews/review.jsx
- client/src/components/ratingsAndReviews/reviews/reviewButtons.jsx
- client/src/components/ratingsAndReviews/reviews/sortingDropdown.jsx
- server/reviews.js
Mainly style update to resemble the visual design more.
Also caught a bug with recommendation rate - updated the related algorithm.
Unit tests still passing.
Manual tests shouldn't have any regression.
Found a layout issue with the review modal in my deployed app so decided to do this ticket first.
https://trello.com/c/nYHCCDaR
> Ratings and reviews style adjustment

- client/src/components/productOverview/ImageGallery.jsx
- client/src/components/productOverview/ImageNavButton.jsx
- client/src/components/productOverview/SelectSize.jsx
- client/src/components/productOverview/testingLibrary/AddToCart.test.js
- client/src/components/productOverview/testingLibrary/ImageGallery.test.js
- client/src/fixtures/testProduct.json
Added tests for ImageGallery and AddToCart components
npm test
https://trello.com/c/TJMNfjXG/177-m-increase-code-coverage-with-more-tests
> Added tests

- client/src/actions/fetchData.js
- client/src/actions/relatedProducts/changeRelatedProducts.js
- client/src/components/Wrapper.jsx
- client/src/components/productOverview/OverviewContainer.jsx
- client/src/components/ratingsAndReviews/ratingsAndReviews.jsx
- client/src/components/relatedProducts/RelatedProducts.jsx
- client/src/reducers/relatedProducts/relatedProductsReducer.js
- client/src/reducers/rootReducer.js
- server/relatedProducts.js
- server/reviews.js
- server/server.js
refactored code to make one initial api call for all widgets instead of 1 in each widget, to optimize performance.
test suites are still passing. also manual testing (e.g. 47426) to make sure all widgets work as expected.
test suites are still passing
https://trello.com/c/UeTnSTzR/176-l-refactor-to-make-one-api-call-from-client-side
> Refact api

- package-lock.json
- package.json
- server/server.js
Given the complexity of peer dependencies of `brotli`, I decided to use `gzip` which doesn't require much and yet bumps the performance a lot!
pull this branch and `npm install`, run lighthouse audition
Am I crazy?
This is for 47421 (404s for photos so maybe affect performance & best practice?)
And this is for 47424
> text compression

- client/dist/bundle.js.LICENSE.txt
- client/src/components/productOverview/Style.jsx
- client/src/components/ratingsAndReviews/reviews/review.jsx
- package-lock.json
- package.json
- webpack.config.js
Added `terser-webpack-plugin` and made some small changes to `webpack.config`
`npm install` first and rerun `npm run react-build`, and do the lighthouse audit
There are some warnings for `npm run react-build` which doesn't affect app behavior though.
> added terser-webpack-plugin

- client/src/actions/toggleColorTheme.js
- client/src/components/common/commonUI.module.css
- client/src/components/common/navBar.jsx
- client/src/components/common/starRating.jsx
- client/src/components/productOverview/AddToCart.jsx
- client/src/components/productOverview/SelectQty.jsx
- client/src/components/productOverview/SelectSize.jsx
- client/src/components/productOverview/styles.css
- client/src/components/ratingsAndReviews/ratings/productBreakdownBar.jsx
- client/src/components/ratingsAndReviews/ratings/starBreakdown.jsx
- client/src/components/ratingsAndReviews/ratings/starBreakdownBar.jsx
- client/src/components/ratingsAndReviews/ratingsAndReviews.module.css
- client/src/components/ratingsAndReviews/reviewModal/reviewModal.jsx
- client/src/components/ratingsAndReviews/reviewModal/reviewModalCharRating.jsx
- client/src/components/ratingsAndReviews/reviewModal/reviewModalOverallRating.jsx
- client/src/components/ratingsAndReviews/reviews/review.jsx
- client/src/components/ratingsAndReviews/reviews/reviewButtons.jsx
- client/src/components/ratingsAndReviews/reviews/sortingDropdown.jsx
- client/src/components/ratingsAndReviews/test/review.test.jsx
- client/src/components/relatedProducts/Modal.jsx
- client/src/components/relatedProducts/styles.css
- client/src/components/relatedProducts/test/modal.test.js
- client/src/components/relatedProducts/test/productCard.test.js
- client/src/reducers/rootReducer.js
- client/src/reducers/toggleColorTheme.js
Sorry for a large PR at this moment! But this is really just CSS change to better fit the dark theme. 
I added `theme` to the redux store since I felt some small components from the review widget may rely on it and modifying `index.html` may eventually make it giant lol.
Some tests are failing because of the addition of redux store, but that's an easy fix so I added `testStore` to those.
Toggle between light and dark theme.
https://trello.com/c/HiAXI9CB
> color theme adjustment
